name       : python-shellingham
version    : 1.5.0
release    : 2
source     :
    - https://pypi.io/packages/source/s/shellingham/shellingham-1.5.0.post1.tar.gz : 823bc5fb5c34d60f285b624e7264f4dda254bc803a3774a147bf99c0e3004a28
license    : MIT
component  : programming.python
summary    : Tool to Detect Surrounding Shell
description: |
    Tool to Detect Surrounding Shell
build      : |
    %python3_setup
install    : |
    %python3_install
