name       : python-shellingham
version    : 1.4.0
release    : 1
source     :
    - https://pypi.io/packages/source/s/shellingham/shellingham-1.4.0.tar.gz : 4855c2458d6904829bd34c299f11fdeed7cfefbf8a2c522e4caea6cd76b3171e
license    : MIT
component  : programming.python
summary    : Tool to Detect Surrounding Shell
description: |
    Tool to Detect Surrounding Shell
build      : |
    %python3_setup
install    : |
    %python3_install
